### ISSUE TITLE
The training of Diffused Human Model.

### ISSUE THREAD

**Issue by liren2515** [isantesteban/vto-garment-collisions#3]
Hello,

Thanks for your great work. It's very interesting.

I'm trying to reimplement the diffused human model used in your work. In Eq. 6 of your paper, you average the **B_p** of N points around **p**. So my question is how you choose p's neighbors. You mentioned **q_n ~ N(p, d)**, does it mean you sample around p with a gaussian distribution where **d** (the distance from p to the surface body) is the std? If so, it may be a little wired for the points that are far away from the body mesh, since **d** would be quite large. And how many points do you use for this averaging?

**Comment by isantesteban** [comment]
Thanks for your kind words! 

> You mentioned q_n ~ N(p, d), does it mean you sample around p with a gaussian distribution where d (the distance from p to the surface body) is the std?

Yes, this is correct. Since the garments are close to the body surface, in practice we only evaluate the diffused human model for low values of **d**. If the averaging becomes a problem for larger values, I suppose it could make sense to limit the value of the std, but we haven't had any issues with that.

>And how many points do you use for this averaging?

We use N=1000 points
