### ISSUE TITLE
Calculation of deformation gradient of unposed garment

### ISSUE THREAD

**Issue by belltailjp** [isantesteban/vto-garment-collisions#4]
Hello, I am quite impressed with the idea of optimization-based unposing to prevent skinning-related artifacts (section 4.3 in the paper), brought me trying to re-implement its concept.

One thing I don't understand well is that how a deformation gradient in strain error between the template and an unposed garment mesh is calculated in this research (Equation 11 in the paper).
Here let me use a notation from [the figure in wikipedia](https://en.wikipedia.org/wiki/Finite_strain_theory#Deformation_gradient_tensor) regarding general deformation gradient tensor ***F*** which is basically defined as
_d**x** = **F** @ d**X**_
where _d**X**_ (3x3 matrix) is a set of small relative vectors around a certain 3D point _X_ on the undeformed surface, _d**x**_ (also 3x3) is corresponding deformed small relative vectors around a point _x_, and _@_ is matmul.
This leads to
_**F** = d**X** \ d**x**_
which can easily be solved for.

My question is that in this research how are _d**X**_ and _d**x**_ set, regarding a triangle (polygon) on the template (ie, _β_ = 0, _θ_ = 0) and an unposed garment meshes, respectively?
I initially thought we can simply use the absolute coordinates of a 3 vertices of a triangle on the template garment mesh as _d**X**_ (so it'll be a 3x3 matrix), and similarly their locations in the unposed mesh as _d**x**_. But it sounds to be inconsistent to the definition of ***F*** above, as well as its numerical instability because of determinants being very close to 0, so I think I am wrong.
To follow the definition more strictly, I also tried considering the center of a triangle (polygon) in the template garment as _X_ and define _d**X**_ as the relative position of each vertex of the triangle, and similarly to _d**x**_, but this also makes det(_d**X**_) = 0 so I guess it's wrong too...

I see this energy term is very important to solve the unposed problem as we get very long unnaturally stretched polygons appear in the unposed mesh without this.
I would really appreciate it if you could make some comments on my question.

**Comment by isantesteban** [comment]
Hi! thanks for your interest in our work 

If you need some guidelines about how to compute deformation gradients I think this Siggraph course is a good starting point: [https://viterbi-web.usc.edu/~jbarbic/femdefo/sifakis-courseNotes-TheoryAndDiscretization.pdf](https://viterbi-web.usc.edu/~jbarbic/femdefo/sifakis-courseNotes-TheoryAndDiscretization.pdf)

Equation 4.3 (Page 28) shows how to compute it for a tetrahedral element. For triangular elements it's quite similar, here is a snippet of our code:

```python
def compute_shape_matrix(x):
    return tf.stack([x[:,0] - x[:,2], x[:,1] - x[:,2]], axis=-1)

triangles_rest = vertices_rest[garment_faces]           # num_triangles × 3 × 2
Dm = compute_shape_matrix(triangles_rest)               # num_triangles × 2 × 2
Dm_inv = tf.linalg.inv(Dm)

triangles_deformed = vertices_deformed[garment_faces]   # num_triangles × 3 × 3
Ds = compute_shape_matrix(triangles_deformed)           # num_triangles × 3 × 2
F = Ds @ Dm_inv # Deformation gradient                  # num_triangles × 3 × 2
```
In our case, the rest configuration of the triangles is given by the 2D patterns of the garment, so `vertices_rest` is a matrix of size `num_vertices × 2`. If you want to take a look at the patterns of the t-shirt they are embedded into the `.obj` file as UV coordinates: [https://github.com/isantesteban/vto-garment-collisions/blob/main/assets/meshes/tshirt.obj](https://github.com/isantesteban/vto-garment-collisions/blob/main/assets/meshes/tshirt.obj)

![image](https://user-images.githubusercontent.com/17111347/156621535-51a82e43-b362-4be7-8d0a-eb3ef165f815.png)

Due to constraints with the sponsor of the project we are not allowed to share the full code, but I hope this is useful!

**Comment by belltailjp** [comment]
Thanks so much for the very prompt and detailed answer!!
The tutorial also helped me a lot, since it explains deformation grads in the CG context.
So basically we evaluate how each polygon deforms from a triangle on the 2D UV space to the unposed 3D mesh.
I think I've learnt what I need to understand implementation level details.
Just to deepen my understanding a little more, I guess we can also define deformation error between the _3D_ template garment mesh in the rest pose and an unposed one, but this research considers that on 2D UV map -> unposed, in my understanding this is mainly because we use triangle meshes, i.e., a pair of 3d triangles cannot determine 3x3 ***F*** matrix in terms of DoF, is this correct?

**Comment by isantesteban** [comment]
I'm glad the tutorial was helpful!! My knowledge of this topic is very limited but I've seen some people implement deformation gradients of triangles as 3x3 matrices. I'm not sure what's the practical advantage of this but here is an example from [ArcSim](http://graphics.berkeley.edu/resources/ARCSim/), in case you want to look into it: https://github.com/zhou13/arcsim/blob/28960d2a70f257459bb9ecfa7d48efda95ce69de/src/physics.cpp#L92

**Comment by belltailjp** [comment]
I see! Maybe I should check for myself for this > deformation grad from 2D->3D or 3D->3D
Anyways my implementation apparently worked well thanks to your advice, though some kind of hyperparameter tuning seems to be still needed.
Thanks again for your prompt and kind answer!
